name: Deploy API to Railway

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'apps/api/**'
      - 'packages/**'
      - '.github/workflows/deploy-api.yml'
  workflow_dispatch:

jobs:
  deploy-api:
    name: Deploy API to Railway
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Install dependencies
        run: npm ci

      - name: Build dependencies
        run: npm run build:deps

      - name: Build API
        run: npm run build --scope=@jarrbank/api

      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          cd apps/api
          railway up --service api

      - name: Get Railway deployment URL
        id: railway-url
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          cd apps/api
          # Railway will output the deployment URL after successful deployment
          echo "✅ API deployment initiated on Railway"
          # Note: URL will be available in Railway dashboard

      - name: Deployment Success
        if: success()
        run: |
          echo "✅ Railway deployment initiated successfully"
          echo "📝 Note: Update NEXT_PUBLIC_API_URL in Vercel with your Railway API URL"
          echo "🔗 Check Railway dashboard for deployment status and URL"